Enable CodeQL
My-DIGI-ID/aries-cloudagent-loadgenerator pull request #1
Opened 2021-12-15 06:58 UTC by geahaad

Create codeql-analysis.yml

2022-01-04 12:03 UTC, holzeis requested changes

2022-01-04 12:03 UTC, holzeis commented on .github/workflows/codeql-analysis.yml
> +        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
let's wait for how we are going to build (what language) the load generator before adding code ql checks.

2022-01-05 07:09 UTC, holzeis commented on .github/workflows/codeql-analysis.yml
> +        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
@geahaad looks like there is currently no kotlin support in codeql. https://github.com/github/codeql/issues/4699

2022-02-08 09:22 UTC, geahaad commented
Closed. No support for Kotlin in CodeQL, yet. (https://github.com/github/codeql/issues/4699)

2022-02-08 09:22 UTC, closed without merging